# Generated by Django 4.1.7 on 2023-03-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_mymodel_rename_subdomain_subdomain_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdomain',
            old_name='subdomains',
            new_name='subdomain',
        ),
    ]
