# Generated by Django 4.1.7 on 2023-03-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_domain_subdomain_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subdomain',
            new_name='Sdomain',
        ),
    ]
