# Generated by Django 4.1.7 on 2023-03-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_subdomain_sdomain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sdomain',
            new_name='Website1',
        ),
    ]
