# Generated by Django 4.1.7 on 2023-03-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_sdomain_website1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website1',
            new_name='Subdomain',
        ),
    ]
