# Generated by Django 4.1.7 on 2023-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_portscanresult_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=50)),
                ('record_type', models.CharField(max_length=10)),
            ],
        ),
    ]
