# Generated by Django 4.1.7 on 2023-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_dnsreconresult_delete_dnsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('asn', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
