# Generated by Django 4.1.7 on 2023-03-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_subdomains_subdomain_subdomain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdomain',
            old_name='domain',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='subdomain',
        ),
        migrations.AddField(
            model_name='subdomain',
            name='subdomains',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
