# Generated by Django 4.1.7 on 2023-03-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_url_subdomain_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdomain',
            old_name='domain',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='subdomain',
        ),
        migrations.AddField(
            model_name='subdomain',
            name='subdomains',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
