# Generated by Django 4.1.7 on 2023-04-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_dnsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsReconResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('dns_record', models.CharField(max_length=255)),
                ('dns_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DNSInfo',
        ),
    ]
