# Generated by Django 4.1.7 on 2023-04-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_websiteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteinfo',
            name='asn',
        ),
        migrations.RemoveField(
            model_name='websiteinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='websiteinfo',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='websiteinfo',
            name='server',
        ),
        migrations.RemoveField(
            model_name='websiteinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
